spring:
  profiles:
    active:
    - dev
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
      location: C:/
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  freemarker:
    check-template-location: false
  
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true

login:
  ldap:
    host: 130.1.22.30
    dn: DC=sy,DC=com
    domain: sy.com
  sso:
    dbip: syc-app02.sy.com
    dbid: LoginInfo
    dbpw: "!1samyang"
    dbname: GetSYUserInfo
    dbdriver: com.microsoft.sqlserver.jdbc.SQLServerDriver
--- #dev
server:
  port: 8080
  error:    include-exception: true # 오류  응답에 exception의 내용을 포함할 지 여부
    include-stacktrace: always # 오류 응답에 stacktrace 내용을 포함할 지 여부
  servlet:    context-path:
spring:
  profiles: dev
  datasource:
    name: Board_DEV
    url: jdbc:sqlserver://syc-app2:1433;databaseName=Board_DEV
    username: syc-app2_admin
    password: "$1Samyang#"
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

logging:
  level:
    org.springframework: DEBUG
    org.springframework.web: DEBUG
    
custom:
  config:
    upload:
      profile-image:
        path: C:\\Side-FileStorage\\Employee-ProfileImage